sudo: false

language: scala
jdk:
  - openjdk8
  - openjdk12
scala:
  - 2.13.0
  - 2.12.8
  - 2.11.12

env:
  - SBT_TASK=core/test
  - SBT_TASK=docs/tut

matrix:
  # https://github.com/scala/bug/issues/11372
  exclude:
    - scala: 2.12.8
      jdk: openjdk12

script:
  - sbt ++$TRAVIS_SCALA_VERSION $SBT_TASK

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
